### ISSUE TITLE
[Quest/Val'sharah] The Corruptor

### ISSUE THREAD

**Issue by bySenom** [wormogo/wow_fixes_for_SPP#28]
total bugged, Boss is spawned with no SAI and it dont count when you kill him
Slay Kagraxxis the Corruptor.

https://www.wowhead.com/quest=39384/the-corruptor

- [x] You can complete the Quest 
- [x] Quest is not blizzlike 
- [x] Quest is buggy
- [x] not working

**Comment by wormogo** [comment]
Quest has been fixed. Closing the ticket
